---
swagger: "2.0"
info:
  version: "2.0.0"
  title: "Stranger Things Wall Server"

# only used for testing
host: "localhost:8080"
schemes:
- "http"
basePath: "/stranger/"
paths:
  /:
    get:
      tags:
      - "default"
      summary: "HTML page to submit stuff"
      operationId: "server.controllers.default_controller.index"
      produces:
      - "text/html; charset=utf-8"
      responses:
        200:
          description: "index page"
  /display:
    post:
      tags:
      - "default"
      summary: "Display message on stranger things board"
      operationId: "server.controllers.default_controller.display"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "message"
        in: "formData"
        description: "message to display"
        required: true
        type: "string"
      responses:
        204:
          description: "Message recieved"
        400:
          description: "Invalid input"
  /messages:
    post:
      tags:
      - "default"
      summary: "Poll for new messages, clear list"
      operationId: "server.controllers.default_controller.messages"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "password"
        in: "formData"
        description: "password for message list"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        200:
          description: "JSON array of messages"
          schema:
            type: "string"
            example: ""
definitions: {}
